"""持久化私聊回应和主动额度。"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0006_private_reply_state"
down_revision = "0005_lazy_lfu_state"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_reply_jobs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('received_seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ai_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('platform_message_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('message_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='accepted', nullable=False),
    sa.Column('claim_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_code', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retain_until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('platform', 'account_id', 'conversation_id', 'platform_message_id'),
    sa.UniqueConstraint('received_seq'),
    sa.UniqueConstraint('run_id'),
    if_not_exists=True,
    )
    op.create_table('private_contact_states',
    sa.Column('ai_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_job_id', sa.BigInteger(), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_run_id', sa.Text(), nullable=True),
    sa.Column('pending_revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='suspended', nullable=False),
    sa.Column('reason_code', sa.Text(), server_default='migration', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unanswered_count BETWEEN 0 AND 3', name='ck_private_count'),
    sa.PrimaryKeyConstraint('ai_id', 'person_id'),
    if_not_exists=True,
    )
    op.create_table('social_deliveries',
    sa.Column('ai_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('source_job_id', sa.BigInteger(), nullable=True),
    sa.Column('claim_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_digest', sa.Text(), nullable=False),
    sa.Column('original_digest', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='prepared', nullable=False),
    sa.Column('platform_message_id', sa.Text(), server_default='', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reason_code', sa.Text(), server_default='', nullable=False),
    sa.Column('history_recorded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ai_id', 'account_id', 'run_id'),
    if_not_exists=True,
    )
    op.create_index('ix_private_reply_ready', 'private_reply_jobs', ['status', 'next_attempt_at'], unique=False,
                    if_not_exists=True)
    op.create_index('ix_private_reply_order', 'private_reply_jobs', ['conversation_id', 'received_seq'], unique=False,
                    if_not_exists=True)
    # ### end Alembic commands ###
    op.execute("INSERT INTO private_contact_states (ai_id, person_id) SELECT ai_id, person_id FROM person_relationships ON CONFLICT DO NOTHING")

def downgrade():
    raise RuntimeError("私聊状态禁止破坏性降级；回滚应用时保留表并关闭主动联系")
