services:
  live-edge:
    image: ailove/live-edge
    container_name: ailove-live-edge-local
    volumes:
    - plugin-state:/app/plugin-state
    - ./config:/app/config:ro
    - ./private/config-secrets:/app/config-secrets:ro
    environment:
    - AILOVE_PLUGIN_STATE_DIR=/app/plugin-state
    - AILOVE_BUS_URL=${AILOVE_BUS_URL:?}
    - AILOVE_BUS_TOKEN=${AILOVE_BUS_TOKEN:?}
    - AILOVE_CONFIG_DIRECTORY=/app/config
    - AILOVE_CONFIG_SECRET_DIRECTORY=/app/config-secrets
    ports:
    - 8081:8081
    restart: unless-stopped
    networks:
    - ailove
  gpt-sovits:
    image: ${GPT_SOVITS_IMAGE:?}
    container_name: ailove-gpt-sovits
    environment:
    - GPT_SOVITS_URL=http://127.0.0.1:9880
    ports:
    - 9880:9880
    volumes:
    - ./sounds:/sounds
    restart: unless-stopped
    networks:
    - ailove
networks:
  ailove:
    driver: bridge
volumes:
  plugin-state: null
